### ISSUE TITLE
Model follows the camera movement

### ISSUE THREAD

**Issue by jessicasFranco** [kalwalt/jsartoolkit5#31]
(Projects inside "nft_improved_worker")

I tryied out the "threejs_worker_gltf" and "threejs_worker_pinball_video". In both when I move my smartphone the model or video follows the smartphone movement. There is any way of making model/video/image movement more smooth?

**Comment by kalwalt** [comment]
Ho @jessicasFranco welcome ! Yes, i know that problem. The reason Is in the tracking algo, the original version is multi-threaded, de can't use that code because required to translate code in Emscripten with pthread enabled. And this solution is faster but has his downside. It required to enabled the Shared ArrayBufffer option in the browser and expose the device to the Spectre issue. We potes for a non threaded version, slower but without thé problem i explained.
We will want to improve this part, if you know or someone else knows a better solution i will very happy! 🙂

**Comment by kalwalt** [comment]
> I tryied out the "threejs_worker_gltf" and "threejs_worker_pinball_video". In both when I move my smartphone the model or video follows the smartphone movement. There is any way of making model/video/image movement more smooth?

@jessicasFranco but did yuu tried the latest?

**Comment by nicolocarpignoli** [comment]
I think we can close this one. If someone find this issue again, on worker versions, a new issue will be opened. We should set only worker version as unique version available.

**Comment by nicolocarpignoli** [comment]
Probably @jessicasFranco used not-updated version.

**Comment by jessicasFranco** [comment]
@nicolocarpignoli  I was using the version in this repo https://github.com/artoolkitx/jsartoolkit5. I downloaded the project  and tried some of the projects. Isn't this the updated version? If not, where I can find it? Thank you!
